// AUTO-GENERATED BY ADMIN TERMINAL
// DO NOT MODIFY MANUALLY. RUN 'node AdminTerminal/generateAssetMap.js' to update!

export const ASSET_MAP: Record<string, any> = {
  "AND_Gate.png": require("../../assets/images/components/AND_Gate.png"),
  "NAND_Gate.png": require("../../assets/images/components/NAND_Gate.png"),
  "NOR_Gate.png": require("../../assets/images/components/NOR_Gate.png"),
  "NOT_Gate.png": require("../../assets/images/components/NOT_Gate.png"),
  "OR_Gate.png": require("../../assets/images/components/OR_Gate.png"),
  "Sensor_DHT11.png": require("../../assets/images/components/Sensor_DHT11.png"),
  "Sensor_HCSR04.png": require("../../assets/images/components/Sensor_HCSR04.png"),
  "Sensor_IR.png": require("../../assets/images/components/Sensor_IR.png"),
  "Sensor_LDR.png": require("../../assets/images/components/Sensor_LDR.png"),
  "Sensor_MQ2.png": require("../../assets/images/components/Sensor_MQ2.png"),
  "Sensor_PIR.png": require("../../assets/images/components/Sensor_PIR.png"),
  "Sensor_Soil.png": require("../../assets/images/components/Sensor_Soil.png"),
  "XNOR_Gate.png": require("../../assets/images/components/XNOR_Gate.png"),
  "XOR_Gate.png": require("../../assets/images/components/XOR_Gate.png"),
};
