const fs = require('fs');
const path = require('path');

const COMPONENTS_DIR = path.join(__dirname, '../ElectroGuide/assets/images/components');
const OUTPUT_FILE = path.join(__dirname, '../ElectroGuide/src/utils/assetMap.ts');
const OUTPUT_DIR = path.dirname(OUTPUT_FILE);

// Ensure the utils directory exists in the React Native project!
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

function generateAssetMap() {
  console.log("🚀 Initializing 100% Offline Asset Binding Engine...");

  if (!fs.existsSync(COMPONENTS_DIR)) {
    console.error("❌ Crucial Error: The components image folder doesn't exist!");
    process.exit(1);
  }

  const files = fs.readdirSync(COMPONENTS_DIR).filter(file => !file.startsWith('.'));
  
  if (files.length === 0) {
    console.log("⚠️ Emitting empty asset map. Your components folder is physically empty.");
  } else {
    console.log(`📂 Crawled ${files.length} physical assets successfully! Generating Native Compiler Code...`);
  }

  let fileContent = `// AUTO-GENERATED BY ADMIN TERMINAL\n`;
  fileContent += `// DO NOT MODIFY MANUALLY. RUN 'node AdminTerminal/generateAssetMap.js' to update!\n\n`;
  fileContent += `export const ASSET_MAP: Record<string, any> = {\n`;

  files.forEach(file => {
    // Escape quotes just in case there are strange file names
    const safeKey = file.replace(/"/g, '\\"');
    fileContent += `  "${safeKey}": require("../../assets/images/components/${file}"),\n`;
  });

  fileContent += `};\n`;

  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log(`\n🎉 MASSIVE SUCCESS! Wrote flawless TypeScript compiler code permanently to:`);
  console.log(`   ${OUTPUT_FILE}`);
  console.log(`Your Android app can now pull these ${files.length} heavily accelerated offline components instantaneously with ZERO internet connection!`);
}

generateAssetMap();
