const admin = require('firebase-admin');
const fs = require('fs');

let serviceAccount;
try {
  serviceAccount = require('./serviceAccountKey.json');
} catch (e) {
  console.error("❌ ERROR: serviceAccountKey.json not found!");
  process.exit(1);
}

if (!admin.apps.length) {
  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount)
  });
}

const db = admin.firestore();

const COMPONENTS = [
  // ================= TRANSISTORS =================
  { cat: "Transistors", name: "NPN Transistor", desc: "Standard Bipolar Junction Transistor where current flows from collector to emitter when base is positive.", symbol: "Q" },
  { cat: "Transistors", name: "PNP Transistor", desc: "Standard Bipolar Junction Transistor where current flows from emitter to collector when base is negative.", symbol: "Q" },
  { cat: "Transistors", name: "Darlington Transistor", desc: "Two bipolar transistors in one package for very high current gain.", symbol: "Q" },
  { cat: "Transistors", name: "Sziklai Pair", desc: "Compound transistor pair similar to Darlington but using one NPN and one PNP.", symbol: "Q" },
  { cat: "Transistors", name: "Digital Transistor", desc: "Transistor with built-in base resistors for direct connection to microcontrollers.", symbol: "Q" },
  { cat: "Transistors", name: "JFET (Junction FET)", desc: "Voltage-controlled transistor that relies on an electric field to control current.", symbol: "Q" },
  { cat: "Transistors", name: "N-Channel JFET", desc: "JFET that conducts when gate-to-source voltage is zero, pinched off by negative voltage.", symbol: "Q" },
  { cat: "Transistors", name: "P-Channel JFET", desc: "JFET that conducts when gate-to-source voltage is zero, pinched off by positive voltage.", symbol: "Q" },
  { cat: "Transistors", name: "MOSFET", desc: "Metal-Oxide-Semiconductor Field-Effect Transistor, extremely common in digital switching.", symbol: "Q" },
  { cat: "Transistors", name: "Enhancement Mode MOSFET", desc: "MOSFET that is normally OFF and requires gate voltage to conduct.", symbol: "Q" },
  { cat: "Transistors", name: "Depletion Mode MOSFET", desc: "MOSFET that is normally ON and requires gate voltage to turn off.", symbol: "Q" },
  { cat: "Transistors", name: "Power MOSFET", desc: "MOSFET designed to handle significant power levels, common in power supplies.", symbol: "Q" },
  { cat: "Transistors", name: "Dual-Gate MOSFET", desc: "MOSFET with two gates, often used in RF mixers and amplifiers.", symbol: "Q" },
  { cat: "Transistors", name: "MESFET", desc: "Metal-Semiconductor FET, typically used in high-frequency microwave communications.", symbol: "Q" },
  { cat: "Transistors", name: "HEMT", desc: "High-Electron-Mobility Transistor, used in extremely high frequency RF applications.", symbol: "Q" },
  { cat: "Transistors", name: "N-Channel IGBT", desc: "Combines the fast switching of a MOSFET with the high current handling of a BJT.", symbol: "Q" },
  { cat: "Transistors", name: "P-Channel IGBT", desc: "P-channel variant of the Insulated Gate Bipolar Transistor.", symbol: "Q" },
  { cat: "Transistors", name: "Unijunction Transistor (UJT)", desc: "Three-terminal device used primarily in free-running oscillators.", symbol: "Q" },
  { cat: "Transistors", name: "Programmable Unijunction Transistor (PUT)", desc: "Similar to UJT but switching parameters can be set via external resistors.", symbol: "Q" },
  { cat: "Transistors", name: "Phototransistor", desc: "A transistor whose base current is generated by exposure to light.", symbol: "Q" },
  { cat: "Transistors", name: "RF / Microwave Transistor", desc: "Transistor heavily optimized for high-frequency radio applications.", symbol: "Q" },
  { cat: "Transistors", name: "Small Signal Transistor", desc: "General purpose transistor for low power amplification and switching.", symbol: "Q" },
  { cat: "Transistors", name: "High Voltage / Power Transistor", desc: "Transistor designed to withstand very high collector-emitter voltages.", symbol: "Q" },

  // ================= DIODES =================
  { cat: "Diodes", name: "Standard PN Junction Diode", desc: "Allows current to flow in only one direction.", symbol: "D" },
  { cat: "Diodes", name: "Schottky Diode", desc: "Diode with a very low forward voltage drop and extremely fast switching action.", symbol: "D" },
  { cat: "Diodes", name: "Fast Recovery Diode", desc: "Rectifier diode that switches off much faster than a standard PN diode.", symbol: "D" },
  { cat: "Diodes", name: "Ultra-Fast Recovery Diode", desc: "Diode optimized for the absolute fastest reverse recovery times in SMPS.", symbol: "D" },
  { cat: "Diodes", name: "Bridge Rectifier", desc: "Array of four diodes arranged to provide full-wave rectification from an AC input.", symbol: "D" },
  { cat: "Diodes", name: "Zener Diode", desc: "Allows current to flow backwards when a specific breakdown voltage is reached. Used for regulation.", symbol: "D" },
  { cat: "Diodes", name: "Transient Voltage Suppression (TVS) Diode", desc: "Used to protect sensitive electronics from voltage spikes and ESD.", symbol: "D" },
  { cat: "Diodes", name: "Avalanche Diode", desc: "Designed to safely operate in reverse breakdown mode without destruction.", symbol: "D" },
  { cat: "Diodes", name: "Crowbar Diode", desc: "Overvoltage protection diode that intentionally short-circuits to blow a fuse.", symbol: "D" },
  { cat: "Diodes", name: "Signal Diode", desc: "Small, fast diode used for processing low-current information signals.", symbol: "D" },
  { cat: "Diodes", name: "Varactor Diode (Varicap)", desc: "Diode whose internal capacitance changes based on the reverse bias voltage.", symbol: "D" },
  { cat: "Diodes", name: "PIN Diode", desc: "Features a wide intrinsic semiconductor region, used heavily as an RF switch.", symbol: "D" },
  { cat: "Diodes", name: "Tunnel Diode (Esaki)", desc: "Capable of very fast operation into the microwave region due to quantum tunneling.", symbol: "D" },
  { cat: "Diodes", name: "Gunn Diode", desc: "Used to generate microwave frequencies via the Gunn effect.", symbol: "D" },
  { cat: "Diodes", name: "Step Recovery Diode", desc: "Generates extremely short pulses, used in microwave multipliers.", symbol: "D" },
  { cat: "Diodes", name: "Backward Diode", desc: "A tunnel diode optimized to rectify very small signals.", symbol: "D" },
  { cat: "Diodes", name: "Photodiode", desc: "Converts light directly into electrical current.", symbol: "D" },
  { cat: "Diodes", name: "Laser Diode", desc: "Produces coherent laser light via stimulated emission.", symbol: "D" },
  { cat: "Diodes", name: "Solar Cell", desc: "A large area photodiode designed specifically to generate power from sunlight.", symbol: "D" },

  // ================= LEDs =================
  { cat: "LEDs", name: "Standard Indicator LED", desc: "Traditional through-hole 3mm, 5mm, or 10mm colored light indicator.", symbol: "LED" },
  { cat: "LEDs", name: "Miniature / Subminiature LED", desc: "Tiny through-hole LED for tight spaces.", symbol: "LED" },
  { cat: "LEDs", name: "SMD (Surface Mount) LED", desc: "Tiny chip LED soldered directly to the surface of a PCB.", symbol: "LED" },
  { cat: "LEDs", name: "Super Bright / Ultra Bright LED", desc: "LED featuring highly transparent epoxy and advanced dies for intense brightness.", symbol: "LED" },
  { cat: "LEDs", name: "COB (Chip on Board) LED", desc: "Multiple LED chips packaged directly onto a substrate for massive light output.", symbol: "LED" },
  { cat: "LEDs", name: "High-Power LED", desc: "1W, 3W, or larger LEDs mounted on metal core PCBs or heatsinks for illumination.", symbol: "LED" },
  { cat: "LEDs", name: "Filament LED", desc: "Vintage-style LED strips designed to look like traditional incandescent filaments.", symbol: "LED" },
  { cat: "LEDs", name: "Bi-Color LED", desc: "Contains two different colored LED dies in a single package.", symbol: "LED" },
  { cat: "LEDs", name: "Tri-Color LED", desc: "Contains three LED dies (often Red, Green, Blue) but lacks an integrated controller.", symbol: "LED" },
  { cat: "LEDs", name: "RGB LED", desc: "Contains Red, Green, and Blue dies to mix millions of colors.", symbol: "LED" },
  { cat: "LEDs", name: "RGBW LED", desc: "RGB LED that includes a dedicated pure White die for better color rendering.", symbol: "LED" },
  { cat: "LEDs", name: "Addressable LED", desc: "RGB LED with a built-in microchip (e.g. WS2812B) allowing daisy-chain digital control.", symbol: "LED" },
  { cat: "LEDs", name: "Flashing / Blinking LED", desc: "Standard LED with an integrated multivibrator chip that blinks automatically.", symbol: "LED" },
  { cat: "LEDs", name: "Infrared LED (IR)", desc: "Emits invisible infrared light, heavily used in remote controls and night vision.", symbol: "LED" },
  { cat: "LEDs", name: "Ultraviolet LED (UV)", desc: "Emits UV light, used for curing resins, counterfeit detection, and sterilization.", symbol: "LED" },
  { cat: "LEDs", name: "7-Segment Display", desc: "Array of 7 LEDs arranged to display numeric digits.", symbol: "LED" },
  { cat: "LEDs", name: "14-Segment / 16-Segment Display", desc: "Expanded array capable of displaying full alphanumeric characters.", symbol: "LED" },
  { cat: "LEDs", name: "Dot Matrix Display", desc: "Grid of LEDs used to display complex graphics or scrolling text.", symbol: "LED" },
  { cat: "LEDs", name: "LED Bar Graph", desc: "Row of distinct LEDs packaged together, often used for audio level meters.", symbol: "LED" }
];

async function run() {
  console.log(`🚀 Injecting ${COMPONENTS.length} Semiconductors into Database...`);
  const batch = db.batch();
  let count = 0;

  for (const comp of COMPONENTS) {
    const docRef = db.collection('components').doc();
    const imageKeyName = comp.name.replace(/[^a-zA-Z0-9_]/g, '_') + '.png';
    
    batch.set(docRef, {
      name: comp.name,
      categoryId: comp.cat, // 'Transistors', 'Diodes', or 'LEDs'
      symbol: comp.symbol,
      description: comp.desc,
      imageKey: imageKeyName,
      imageUrl: "placeholder"
    });
    count++;
  }

  await batch.commit();
  console.log(`✅ EPIC SUCCESS! All ${count} items securely injected!`);
  
  const filenames = COMPONENTS.map(c => c.name.replace(/[^a-zA-Z0-9_]/g, '_') + '.png');
  fs.writeFileSync('./semi_filenames.json', JSON.stringify(filenames, null, 2));
  console.log(`✅ Saved required filenames to semi_filenames.json`);
}

run();
