name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      EXPO_PUBLIC_FIREBASE_API_KEY: AIzaSyAdqSjaT9bqFfLTo5jEuA5ILVGAzJHFkZ8
      EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN: levidex.firebaseapp.com
      EXPO_PUBLIC_FIREBASE_PROJECT_ID: levidex
      EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET: levidex.firebasestorage.app
      EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 1030103160013
      EXPO_PUBLIC_FIREBASE_APP_ID: 1:1030103160013:web:2641d5aa76234822d18584
      EXPO_PUBLIC_FIREBASE_MEASUREMENT_ID: G-MZCCQMQ3E5
      NODE_OPTIONS: --max_old_space_size=2048

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        working-directory: ./ElectroGuide
        run: npm install

      - name: Expo Prebuild (Generate Native Android folder)
        working-directory: ./ElectroGuide
        run: npx expo prebuild --platform android --clean

      - name: Fix OOM by increasing Gradle memory
        working-directory: ./ElectroGuide/android
        run: sed -i 's/org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m/org.gradle.jvmargs=-Xmx3072m -XX:MaxMetaspaceSize=1024m/' gradle.properties

      - name: Build APK (Gradle assembleRelease)
        working-directory: ./ElectroGuide/android
        run: ./gradlew assembleRelease -x lint

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LEVIDEX-App-APK
          path: ./ElectroGuide/android/app/build/outputs/apk/release/app-release.apk

